version: '3'
services:
  rabbitmq:
    # image: rabbitmq:3-management
    build: 
      dockerfile: ./Dockerfile_rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672   # RabbitMQ
      - 15672:15672 # Management console
    expose:
      - 5672
      - 15672
    environment:
      RABBITMQ_DEFAULT_USER: trampar
      RABBITMQ_DEFAULT_PASS: trampar-de-casa
    # command: 
  redis:
    image: redislabs/redismod
    ports:
      - '6379:6379'
    expose:
      - 6379
  roles-validator:
    build: 
      dockerfile: ./roles-validator-image
    env_file:
      - apps/workers/roles-validator/.env
    depends_on:
      - redis
  roles-renderer:
    build: 
      dockerfile: ./roles-renderer-image
    env_file:
      - apps/workers/roles-renderer/.env
    depends_on:
      - redis
  roles-assigner:
    build: 
      dockerfile: ./roles-assigner-image
    env_file:
      - apps/workers/roles-assigner/.env
    depends_on:
      - redis
      - roles-validator
      - rabbitmq
  email-pre-renderer:
    build: 
      dockerfile: ./email-pre-renderer-image
    env_file:
      - apps/workers/email-pre-renderer/.env
    depends_on:
      - redis
      - rabbitmq
  email-composer:
    build: 
      dockerfile: ./email-composer-image
    env_file:
      - apps/workers/email-composer/.env
    depends_on:
      - redis
      - rabbitmq
  email-sender:
    build: 
      dockerfile: ./email-sender-image
    env_file:
      - apps/workers/email-sender/.env
    depends_on:
      - rabbitmq
